partitech_afb_upload:
  path: /partitechadvancedform/upload
  controller: "partitech_afb.file_upload.controller::uploadFileAction"

partitech_afb_remove:
  path: /partitechadvancedform/remove
  controller: "partitech_afb.file_upload.controller::removeFileAction"

partitech_afb_upload_tmp:
  path: /partitechadvancedform/upload_tmp
  controller: "partitech_afb.file_upload.controller::uploadTmpAction"

partitech_afb_remove_tmp:
  path: /partitechadvancedform/remove_tmp
  controller: "partitech_afb.file_upload.controller::removeTmpFileAction"

partitech_afb_preview:
  path: /partitechadvancedform/uploaded/{token}
  controller: "partitech_afb.file_upload.controller::viewUploadedFileAction"

partitech_afb_dependent_results:
  path: /Partitechadvancedform/dependent-result
  controller: "partitech_afb.dependent_entity.controller::getDependentResultsAction"
